name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2

      - name: Install ocamlformat
        run: opam install ocamlformat.0.22.4
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Install opam packages
        run: opam install . --with-test

      - name: Check formatting
        run: dune build @fmt

      - name: Run build
        run: dune build
